../env/bin/python3 train.py \
  --dataset_name 'zara1' \
  --delim tab \
  --d_type 'local' \
  --pred_len 8 \
  --encoder_h_dim_g 32 \
  --encoder_h_dim_d 64\
  --decoder_h_dim 32 \
  --embedding_dim 16 \
  --bottleneck_dim 32 \
  --mlp_dim 64 \
  --num_layers 1 \
  --noise_dim 2 \
  --noise_type inject_goal \
  --noise_mix_type individual \
  --pool_every_timestep 0 \
  --l2_loss_weight 1 \
  --intention_loss_weight 1\
  --batch_norm 0 \
  --dropout 0 \
  --batch_size 32 \
  --g_learning_rate 1e-3 \
  --g_steps 1 \
  --d_learning_rate 1e-3 \
  --d_steps 2 \
  --checkpoint_every 10 \
  --print_every 50 \
  --num_iterations 20000 \
  --num_epochs 500 \
  --pooling_type 'pool_net' \
  --clipping_threshold_g 1.5 \
  --best_k 1 \
  --gpu_num 1 \
  --checkpoint_name inject_exit_point \
  --restore_from_checkpoint 0
